import Head from "next/head";
import HeaderClient from "../../../../components/parts/clients/header";
import StadiumRecherche from "../../../../components/parts/clients/search";
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import interactionPlugin from "@fullcalendar/interaction";
import timeGridPlugin from "@fullcalendar/timegrid";
import JsFiles from "../../../../components/parts/packages/jsFiles";
import {Rate} from "antd";
import StadiumsList from "../../../../components/parts/clients/stadiums";

export default function SpecificReservation(props){

    function ratePlayer(e){
        console.log(e)
    }
    return (
        <>
            <Head>
                <title>Reservations</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <HeaderClient/>
            <main>
                <div className="container-fluid page-header mb-5 p-0" style={{backgroundImage: 'url(img/carousel-1.jpg)'}}>
                    <div className="container-fluid page-header-inner py-5">
                        <div className="container text-center pb-5">
                            <h1 className="display-3 text-white mb-3 animated slideInDown">Reservation</h1>
                            <nav aria-label="breadcrumb">
                                <ol className="breadcrumb justify-content-center text-uppercase">
                                    <li className="breadcrumb-item"><a href="#">Home</a></li>
                                    <li className="breadcrumb-item"><a href="#">Profile</a></li>
                                    <li className="breadcrumb-item text-white active" aria-current="page">Reservations</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>

                <div className="container-xxl py-5">
                    <div className="container">
                        <div className="text-center wow fadeInUp" data-wow-delay="0.1s">
                            <h6 className="section-title text-center text-primary text-uppercase">TeamS</h6>
                            <h1 className="mb-5">Rate your <span className="text-primary text-uppercase">Players</span></h1>
                        </div>
                        <div className="row g-4">
                            <div className="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                                <div className="rounded shadow overflow-hidden">
                                    <div className="position-relative">
                                        <img className="img-fluid" src="/img/team-1.jpg" alt="" />
                                    </div>
                                    <div className="text-center p-4 mt-1">
                                        <h5 className="fw-bold mb-0">Full Name</h5>
                                        <Rate defaultValue={3} onChange={ratePlayer} style={{color:"#FEA116"}}  />;
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                                <div className="rounded shadow overflow-hidden">
                                    <div className="position-relative">
                                        <img className="img-fluid" src="/img/team-2.jpg" alt="" />
                                        <div className="position-absolute start-50 top-100 translate-middle d-flex align-items-center">
                                            <a className="btn btn-square btn-primary mx-1" href><i className="fab fa-facebook-f" /></a>
                                            <a className="btn btn-square btn-primary mx-1" href><i className="fab fa-twitter" /></a>
                                            <a className="btn btn-square btn-primary mx-1" href><i className="fab fa-instagram" /></a>
                                        </div>
                                    </div>
                                    <div className="text-center p-4 mt-3">
                                        <h5 className="fw-bold mb-0">Full Name</h5>
                                        <Rate value={3} />;
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
                                <div className="rounded shadow overflow-hidden">
                                    <div className="position-relative">
                                        <img className="img-fluid" src="/img/team-3.jpg" alt="" />
                                        <div className="position-absolute start-50 top-100 translate-middle d-flex align-items-center">
                                            <Rate value={3} />;
                                        </div>
                                    </div>
                                    <div className="text-center p-4 mt-3">
                                        <h5 className="fw-bold mb-0">Full Name</h5>
                                        <Rate value={3} />;
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.7s">
                                <div className="rounded shadow overflow-hidden">
                                    <div className="position-relative">
                                        <img className="img-fluid" src="/img/team-4.jpg" alt="" />
                                        <div className="position-absolute start-50 top-100 translate-middle d-flex align-items-center">
                                            <a className="btn btn-square btn-primary mx-1" href><i className="fab fa-facebook-f" /></a>
                                            <a className="btn btn-square btn-primary mx-1" href><i className="fab fa-twitter" /></a>
                                            <a className="btn btn-square btn-primary mx-1" href><i className="fab fa-instagram" /></a>
                                        </div>
                                    </div>
                                    <div className="text-center p-4 mt-3">
                                        <h5 className="fw-bold mb-0">Full Name</h5>
                                        <small>Designation</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/*<StadiumsList pitches={props.pitches}/>*/}
            </main>
            {/*<FooterClient/>*/}

            <JsFiles/>

        </>

    )
}
export async function getServerSideProps(context) {
    // Fetch data from external API
    const {id} = context.query
    const res = await fetch(`http://localhost:8080/api/pitches/` + id)
    const pitches = await res.json()


    const res2 = await fetch(`http://localhost:8080/api/reservations/` + id)
    const reservations = await res2.json()



    // Pass data to the page via props
    return {props: {pitches, reservations,villes}}
}
