import Head from "next/head";
import HeaderClient from "../../../components/parts/clients/header";
import {Formik} from "formik";
import JsFiles from "../../../components/parts/packages/jsFiles";

export default function AdminLogin(props) {
    return (
        <>
            <Head>
                <title>Admin Login</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>

                <div className="container-xxl py-5">
                    <div className="container">
                        <div className="text-center wow fadeInUp" data-wow-delay="0.1s">
                            <h6 className="section-title text-center text-primary text-uppercase">Auhtentication</h6>
                            <h1 className="mb-5">Section <span
                                className="text-primary text-uppercase">Login</span>
                            </h1>
                        </div>
                        <div className="row g-5">
                            <div className="col-lg-6">
                                <div className="row g-3">
                                    <div className="col-6 text-end">
                                        <img className="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.1s"
                                             src="/img/about-1.jpg" style={{marginTop: '25%'}}/>
                                    </div>
                                    <div className="col-6 text-start">
                                        <img className="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.3s"
                                             src="/img/about-2.jpg"/>
                                    </div>
                                    <div className="col-6 text-end">
                                        <img className="img-fluid rounded w-50 wow zoomIn" data-wow-delay="0.5s"
                                             src="/img/about-3.jpg"/>
                                    </div>
                                    <div className="col-6 text-start">
                                        <img className="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.7s"
                                             src="/img/about-4.jpg"/>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <Formik
                                    initialValues={{email: '', password: '', role: 'client'}}
                                    validate={values => {
                                        const errors = {};
                                        if (!values.email) {
                                            errors.email = 'Required';
                                        } else if (
                                            !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(values.email)
                                        ) {
                                            errors.email = 'Invalid email address';
                                        }
                                        return errors;
                                    }}
                                    onSubmit={(values, {setSubmitting}) => {
                                        // loginSubmit(values)
                                        console.log('here' )
                                        // route.push('/')

                                    }}
                                >
                                    {({
                                          values,
                                          errors,
                                          touched,
                                          handleChange,
                                          handleBlur,
                                          handleSubmit,
                                          isSubmitting,
                                          section,

                                          /* and other goodies */
                                      }) => (

                                        <div className="wow fadeInUp" data-wow-delay="0.2s">
                                            <form onSubmit={handleSubmit}>
                                                <div className="row g-3">
                                                    <div className="col-md-12">
                                                        <div className="form-floating">
                                                            <input type="email" className="form-control"
                                                                   name="email"
                                                                   placeholder="Your Email"
                                                                   onChange={handleChange}/>
                                                            <label htmlFor="name">Your Email</label>
                                                        </div>
                                                        {errors.email && touched.email && errors.email}

                                                    </div>
                                                    <div className="col-md-12">
                                                        <div className="form-floating">
                                                            <input type="password" className="form-control"
                                                                   name="password"
                                                                   placeholder="Your password"
                                                                   onChange={handleChange}/>
                                                            <label htmlFor="password">Your Password</label>
                                                        </div>
                                                        {errors.password && touched.password && errors.password}

                                                    </div>
                                                    <div className="col-12">
                                                        <button type="submit"
                                                                className="btn btn-primary w-100 py-3">
                                                            Sign In
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    )}
                                </Formik>

                            </div>
                        </div>
                    </div>
                </div>
            </main>
            {/*<FooterClient/>*/}

            <JsFiles/>

        </>

    )
}