import Head from 'next/head'
// import Image from 'next/image'
import HeaderClient from "../components/parts/clients/header";
import FooterClient from "../components/parts/clients/footer";
// import styles from '../styles/Home.module.css'
import bg1 from "../public/img/slider-bg-1.jpg"
import bg2 from "../public/img/slider-bg-2.jpg"
import bg3 from "../public/img/slider-bg-3.jpg"
import bg4 from "../public/img/video-bg.jpg"
import bg5 from "../public/img/cta-bg.jpg"
import bg6 from "../public/img/trainer-bg.jpg"


import {Image} from 'antd';
import jsFiles from "../components/parts/clients/jsFiles";
import Stadiums from "../components/stadiums";
import JsFiles from "../components/parts/packages/jsFiles";

export default function Home(props) {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <HeaderClient/>

            <main>
                <div>
                    {/* Hero Section Begin */}
                    <section className="hero-section">
                        <div className="hero-items owl-carousel">
                            <div className="single-hero-item set-bg" data-setbg="img/slider-bg-1.jpg"
                                 style={{backgroundImage: `url(${bg1.src})`}}>
                                <div className="container">
                                    <div className="hero-text">
                                        <h4>Elite Personal Training Services</h4>
                                        <h1>Make it <span>Shape</span></h1>
                                        <a href="#" className="primary-btn">Join Us Now</a>
                                    </div>
                                </div>
                            </div>
                            <div className="single-hero-item set-bg" data-setbg="img/slider-bg-2.jpg"
                                 style={{backgroundImage: `url(${bg2.src})`}}>
                                <div className="container">
                                    <div className="hero-text">
                                        <h4>Elite Personal Training Services</h4>
                                        <h1>Make it <span>Shape</span></h1>
                                        <a href="#" className="primary-btn">Join Us Now</a>
                                    </div>
                                </div>
                            </div>
                            <div className="single-hero-item set-bg" data-setbg="img/slider-bg-3.jpg"
                                 style={{backgroundImage: `url(${bg3.src})`}}>
                                <div className="container">
                                    <div className="hero-text">
                                        <h4>Elite Personal Training Services</h4>
                                        <h1>Make it <span>Shape</span></h1>
                                        <a href="#" className="primary-btn">Join Us Now</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    {/* Hero Section End */}
                    {/* Services Section Begin */}
                    <section className="services-section spad">
                        <div className="container">
                            <div className="row">
                                <div className="col-lg-6">
                                    <div className="section-title">
                                        <h2>Our Program</h2>
                                        <p>Our fitness experts can help you discover new training techniques and
                                            exercises that offer a
                                            dynamic and efficient full-body workout.</p>
                                    </div>
                                    <div className="services-items">
                                        <div className="single-service-item">
                                            <Image src="img/icon-1.png" alt=""/>
                                            <h5>Weight Lifting</h5>
                                            <p>We have a wide choice of classes that are a great complement to any
                                                training programme.
                                            </p>
                                        </div>
                                        <div className="single-service-item color-1">
                                            <Image src="img/icon-2.png" alt=""/>
                                            <h5>Body Building</h5>
                                            <p>We have a wide choice of classes that are a great complement to any
                                                training programme.
                                            </p>
                                        </div>
                                        <div className="single-service-item color-2">
                                            <Image src="img/icon-3.png" alt=""/>
                                            <h5>Healthy</h5>
                                            <p>We have a wide choice of classes that are a great complement to any
                                                training programme.
                                            </p>
                                        </div>
                                        <div className="single-service-item color-3">
                                            <Image src="img/icon-4.png" alt=""/>
                                            <h5>Yoga</h5>
                                            <p>We have a wide choice of classes that are a great complement to any
                                                training programme.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div className="col-lg-5 offset-lg-1">
                                    <div className="service-video set-bg" data-setbg="img/video-bg.jpg"
                                         style={{backgroundImage: `url(${bg4.src})`}}>
                                        <div className="play-btn">
                                            <a href="https://www.youtube.com/watch?v=SlPhMPnQ58k"
                                               className="service-video-popup"><i className="fa fa-play"/></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    {/* Services Section End */}
                    {/* Cta Section Begin */}
                    <section className="cta-section set-bg spad" data-setbg="img/cta-bg.jpg"
                             style={{backgroundImage: `url(${bg5.src})`}}>
                        <div className="container">
                            <div className="row">
                                <div className="col-lg-12">
                                    <h2>Start your Journey with our exciting offers</h2>
                                    <p>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                                    <a href="#" className="primary-btn">Join With Us</a>
                                </div>
                            </div>
                        </div>
                    </section>
                    {/* Cta Section End */}
                    {/* Class Section Begin*/}
                    <section className="class-section spad">
                        <div className="container">
                            <div className="row">
                                <div className="col-lg-12">
                                    <div className="row">
                                        <div className="col-lg-6">
                                            <div className="section-title">
                                                <h2>Our Stadiums</h2>
                                                <p>Our fitness experts can help you discover new training techniques and
                                                    exercises that
                                                    offer a dynamic and efficient full-body workout.</p>
                                            </div>
                                        </div>
                                        <div className="col-lg-6">
                                            <a href="#" className="primary-btn">View All Schedule</a>
                                        </div>
                                    </div>

                                    <Stadiums pitches={props.pitches}/>
                                </div>
                            </div>
                        </div>
                    </section>
                    {/* Class Section End */}
                    {/* Trainer Table Schedule Section Begin */}
                    {/* Team Section Begin */}
                    <section className="team-section spad">
                        <div className="container">
                            <div className="row">
                                <div className="col-lg-12">
                                    <div className="section-title">
                                        <h2>Our Stadiums</h2>
                                        <p>Our fitness experts can help you discover new training techniques.</p>
                                    </div>
                                    <a href="#" className="primary-btn">View All <i className="ti-angle-double-right"/></a>
                                </div>
                            </div>
                            <div className="team-members">
                                <div className="row m-0">
                                    <div className="col-lg-4 order-lg-1 p-0">
                                        <div className="member-pic first">
                                            <Image src="img/trainer-1.jpg" alt=""/>
                                        </div>
                                    </div>
                                    <div className="col-lg-4 order-lg-2 p-0">
                                        <div className="member-text">
                                            <span>Gymer</span>
                                            <h5>Martin Alex</h5>
                                            <p>Body Building, the original LES MILLS barbell class, will sculpt, tone
                                                and strengthen
                                                your entire body, fast!</p>
                                            <div className="member-social">
                                                <a href="#"><i className="ti-facebook"/></a>
                                                <a href="#"><i className="ti-twitter-alt"/></a>
                                                <a href="#"><i className="ti-pinterest"/></a>
                                                <a href="#"><i className="ti-vimeo-alt"/></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-lg-4 order-lg-3 p-0">
                                        <div className="member-pic second">
                                            <Image src="img/trainer-2.jpg" alt=""/>
                                        </div>
                                    </div>
                                    <div className="col-lg-4 order-lg-6 p-0">
                                        <div className="member-text second">
                                            <span>Body Building</span>
                                            <h5>Martin Alex</h5>
                                            <p>Body Building, the original LES MILLS barbell class, will sculpt, tone
                                                and strengthen
                                                your entire body, fast!</p>
                                            <div className="member-social">
                                                <a href="#"><i className="ti-facebook"/></a>
                                                <a href="#"><i className="ti-twitter-alt"/></a>
                                                <a href="#"><i className="ti-pinterest"/></a>
                                                <a href="#"><i className="ti-vimeo-alt"/></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-lg-4 order-lg-5 p-0">
                                        <div className="member-pic third">
                                            <Image src="img/trainer-3.jpg" alt=""/>
                                        </div>
                                    </div>
                                    <div className="col-lg-4 order-lg-4 p-0">
                                        <div className="member-text third">
                                            <span>Yoga</span>
                                            <h5>Martin Alex</h5>
                                            <p>Body Building, the original LES MILLS barbell class, will sculpt, tone
                                                and strengthen
                                                your entire body, fast!</p>
                                            <div className="member-social">
                                                <a href="#"><i className="ti-facebook"/></a>
                                                <a href="#"><i className="ti-twitter-alt"/></a>
                                                <a href="#"><i className="ti-pinterest"/></a>
                                                <a href="#"><i className="ti-vimeo-alt"/></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    {/* Team Section End */}
                    {/* Latest News Section Begin */}
                    {/* Latest News Section End */}
                </div>


            </main>


            <FooterClient/>
            {/* Search model Begin */}
            <div className="search-model">
                <div className="h-100 d-flex align-items-center justify-content-center">
                    <div className="search-close-switch">+</div>
                    <form className="search-model-form">
                        <input type="text" id="search-input" placeholder="Search here....."/>
                    </form>
                </div>
            </div>
            <JsFiles/>

        </>


    )
}
export async function getServerSideProps() {
    // Fetch data from external API
    const res = await fetch(`http://localhost:8080/api/pitches`)
    const pitches = await res.json()

    // Pass data to the page via props
    return {props: {pitches}}
}

